name: build
on: [push, pull_request]

jobs:
    app:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build package
              run: docker-compose up --build build

            - name: Build docs
              run: docker-compose up --build docs

            - name: Try building Jupyter lab
              run: docker-compose build jupyter-lab

            - name: Deploy docs
              if: github.ref == 'refs/heads/master'
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
              run: ./scripts/deploy-docs.sh

            - name: Deploy to NPM
              if: startsWith(github.ref, 'refs/tags/v')
              uses: JS-DevTools/npm-publish@v1
              with:
                  package: ./js/package.json
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Deploy to PyPI
              if: startsWith(github.ref, 'refs/tags/v')
              uses: pypa/gh-action-pypi-publish@master
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
